# These values are all the default values and can be left empty with the same result (except the email section).
# If you want to set the config via UI, you must remove the file mounting in your docker compose file.

general:
  appName: "Pingvin Share Custom" # Name of the application
  secureCookies: false # Whether to set the secure flag on cookies. If enabled, the site will not function when accessed over HTTP.
  showHomePage: true # Whether to show the home page
  sessionDuration: "3 months" # Time in hours after which a user must log in again (default: 3 months).

share:
  allowRegistration: true # Whether registration is allowed
  allowUnauthenticatedShares: false # Whether unauthenticated users can create shares
  maxExpiration: 0 days # Whether unauthenticated users can create shares
  shareIdLength: 8 # Maximum share expiration. Set to 0 to allow unlimited expiration.
  maxSize: 1000000000 # Default length for the generated ID of a share. This value is also used to generate links for reverse shares. A value below 8 is not considered secure.
  zipCompressionLevel: 9 # Adjust the level to balance between file size and compression speed. Valid values range from 0 to 9, with 0 being no compression and 9 being maximum compression.
  chunkSize: 10000000 # Adjust the chunk size for your uploads to balance efficiency and reliability according to your internet connection. Smaller chunks can enhance success rates for unstable connections, while larger chunks make uploads faster for stable connections.
  autoOpenShareModal: false # The share creation modal automatically appears when a user selects files, eliminating the need to manually click the button.

smtp:
  enabled: false # Whether SMTP is enabled. Only set this to true if you entered the host, port, email, user and password of your SMTP server.
  allowUnauthorizedCertificates: false # Only set this to true if you need to trust self signed certificates.
  host: "" # Host of the SMTP server
  port: 0 # Port of the SMTP server
  email: "" # Email address from wich the emails get sent
  username: "" # Username of the SMTP server
  password: "" # Password of the SMTP server

ldap:
  enabled: false # Use LDAP authentication for user login
  url: "" # URL of the LDAP server
  bindDn: "" # Default user used to perform the user search
  bindPassword: "" # Password used to perform the user search
  searchBase: "" # Base location, where the user search will be performed
  searchQuery: "" # The user query will be used to search the 'User base' for the LDAP user. %username% can be used as the placeholder for the user given input.
  adminGroups: "" # Group required for administrative access.
  fieldNameMemberOf: "memberOf" # LDAP attribute name for the groups, an user is a member of. This is used when checking for the admin group.
  fieldNameEmail: "userPrincipalName" # LDAP attribute name for the email of an user.

oauth:
  allowRegistration: false # Allow users to register via social login
  ignoreTotp: false # Whether to ignore TOTP when user using social login
  disablePassword: false # Whether to disable password login. Make sure that an OAuth provider is properly configured before activating this configuration to avoid being locked out.
  githubEnabled: false # Whether GitHub login is enabled
  githubClientId: "" # Client ID of the GitHub OAuth app
  githubClientSecret: "" # Client secret of the GitHub OAuth app
  googleEnabled: false # Whether Google login is enabled
  googleClientId: "" # Client ID of the Google OAuth app
  googleClientSecret: "" # Client secret of the Google OAuth app
  microsoftEnabled: false # Whether Microsoft login is enabled
  microsoftTenant: "" # Tenant ID of the Microsoft OAuth app; common: Users with both a personal Microsoft account and a work or school account from Microsoft Entra ID can sign in to the application. organizations: Only users with work or school accounts from Microsoft Entra ID can sign in to the application.; consumers: Only users with a personal Microsoft account can sign in to the application. domain name of the Microsoft Entra tenant or the tenant ID in GUID format: Only users from a specific Microsoft Entra tenant (directory members with a work or school account or directory guests with a personal Microsoft account) can sign in to the application.
  microsoftClientId: "" # Client ID of the Microsoft OAuth app
  microsoftClientSecret: "" # Client secret of the Microsoft OAuth app
  discordEnabled: false # Whether Discord login is enabled
  discordLimitedGuild: "" # Limit signing in to users in a specific server. Leave it blank to disable.
  discordLimitedUsers: "" # Limit signing in to specific users by their Discord ID. Leave it blank to disable.
  discordClientId: "" # Client ID of the Discord OAuth app
  discordClientSecret: "" # Client secret of the Discord OAuth app
  oidcEnabled: false # Whether OpenID Connect login is enabled
  oidcDiscoveryUri: "" # Discovery URI of the OpenID Connect OAuth app
  oidcSignOut: false # Whether the “Sign out” button will sign out from the OpenID Connect provider
  oidcScope: "" # Scopes which should be requested from the OpenID Connect provider.
  oidcUsernameClaim: "" # Username claim in OpenID Connect ID token. Leave it blank if you don't know what this config is.
  oidcRolePath: "" # Must be a valid JMES path referencing an array of roles. Managing access rights using OpenID Connect roles is only recommended if no other identity provider is configured and password login is disabled. Leave it blank if you don't know what this config is.
  oidcRoleGeneralAccess: "" # Role required for general access. Must be present in a user’s roles for them to log in. Leave it blank if you don't know what this config is.
  oidcRoleAdminAccess: "" # Role required for administrative access. Must be present in a user’s roles for them to access the admin panel. Leave it blank if you don't know what this config is.
  oidcClientId: "" # Client ID of the OpenID Connect OAuth app
  oidcClientSecret: "" # Client secret of the OpenID Connect OAuth app

s3:
  enabled: false # Whether S3 should be used to store the shared files instead of the local file system.
  endpoint: "" # The URL of the S3 bucket.
  region: "" # The region of the S3 bucket.
  bucketName: "" # The name of the S3 bucket.
  bucketPath: "" # The default path which should be used to store the files in the S3 bucket.
  key: "" # The key which allows you to access the S3 bucket.
  secret: "" # The secret which allows you to access the S3 bucket.

legal:
  enabled: false # Whether to show a link to imprint and privacy policy in the footer.
  imprintText: "" # The text which should be shown in the imprint. Supports Markdown. Leave blank to link to an external imprint page.
  imprintUrl: "" # If you already have an imprint page you can link it here instead of using the text field.
  privacyPolicyText: "" # The text which should be shown in the privacy policy. Supports Markdown. Leave blank to link to an external privacy policy page.
  privacyPolicyUrl: "" # If you already have a privacy policy page you can link it here instead of using the text field.

# This is only via the config.yaml file available.
# Consider that you should not use `admin` or this `admin@example.com` as, and definitely not this password
# as your final credentials. It is highly recommended to change the password after the setup.
initUser:
  enabled: false
  username: "admin"
  email: "admin@example.com"
  password: "my-secure-password"
  isAdmin: true
  ldapDN: ""